version: 2.1
resource_types:
  # Set status of build in github for master
  - name: github-status
    type: docker-image
    source:
      repository: resource/github-status
      tag: master

resources:
  - name: code
    type: git
    source:
      uri: https://github.com/luispabon/superagent-retry-delay.git
      branch: master

  - name: master-status
    type: github-status
    source:
      repo: luispabon/superagent-retry-delay
      access_token: {{github-access-token}}

jobs:
  - name: analyze-master
    public: true
    plan:
      - get: code
        trigger: true

      - put: notify-master-being-built
        resource: master-status
        params: { state: "pending", commit: "code" }

      - task: run-tests
        file: code/concourse/task-run-tests.yaml
        params:
          CODECOV_TOKEN: {{codecov-token}}
        on_failure:
          put: master-status
          params: { state: "failure", commit: "code" }

      - task: npm-publish
        file: code/concourse/task-npm-publish.yaml
        params:
          NPM_TOKEN: {{npm-token}}
        on_failure:
          put: master-status
          params: { state: "failure", commit: "code" }

      - put: notify-build-success
        resource: master-status
        params: { state: "success", commit: "code" }
