name: "Test application"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_container:
          - node:12-alpine

    env:
      NODE_CONTAINER: ${{ matrix.node_container }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Initialise environment
        run: make install

      - name: Linting
        run: make lint

#      - name: Upload coverage
#        run: |
#          apt update
#          apt install git --no-install-recommends -y
#          make upload-coverage

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#          files: ./reports/phpunit/coverage.xml # optional
#          flags: unittests # optional
#          name: codecov-umbrella # optional
#          fail_ci_if_error: true # optional (default = false)
          verbose: false # optional (default = false)
